"use client";
import dynamic from "next/dynamic";
const Lines = dynamic(() => import("@/components/lines"), { ssr: false });
import Image from "next/image";
import InfoPopover from "@/components/info-popover";

export default function Section5() {
  return (
    <section className="relative scroll-mt-8 bg-white pt-10 xl:pt-20" id="section-5">
      <Lines
        verticalClassName="px-[152px]"
        sectionName="section-5"
        rows={[]}
        columnsNumber={2}
        colorClass="bg-blue-900/10"
      />
      <div className="container flex flex-col items-start justify-between px-[20px] xl:flex-row xl:px-[150px]">
        <div className="flex gap-[69px] pb-6 xl:pb-[120px]">
          <div className="max-w-[630px] space-y-5 text-green-700 xl:min-w-[630px] xl:pb-10">
            <h2 className="pb-6 text-3xl font-medium xl:pb-16 xl:text-4xl">
              Towards data streaming for efficient uptake by users.
            </h2>
            <div className="max-w-[487px]">
              <h3 className="pb-5 text-xl xl:text-2xl">
                Current practice is that data generated from lower-resolution climate models is
                stored to disk.
              </h3>
              <div>
                <p className="pb-5 text-sm xl:text-base">
                  However, this approach is no longer suitable for the km-scale simulations produced
                  by the digital twin, which call for users to be able to read and capture the
                  information they need while the digital twin is running.
                </p>
                <p>
                  This challenge is solved by the streaming{" "}
                  <InfoPopover
                    content={
                      <>
                        The streaming of the model output gives users immediate access to the
                        complete set of climate data generated by the models in a standardised
                        format across different models and model components (source:{" "}
                        <a
                          target="_blank"
                          className="hover:underline"
                          href="https://www.ecmwf.int/"
                        >
                          ECMWF
                        </a>
                        )
                      </>
                    }
                  >
                    concept
                  </InfoPopover>
                  , which brings the climate models and impact models within the same workflow,
                  significantly transforming the way climate research has been performed and
                  adopting a user-centred setup. Data streaming allows the output of the digital
                  twin to be handled on-the-fly as it is being produced, therefore lowering memory
                  requirements significantly.
                </p>
              </div>
            </div>
          </div>
        </div>
        <Image
          alt=""
          className="pb-[102px] max-xl:max-h-[600px] xl:ml-24"
          src="/images/home-towards-data.svg"
          width={1160}
          height={742}
        />
      </div>
    </section>
  );
}
