import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";
import Header from "@/components/header";

const fontSans = Roboto({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "400", "500", "700", "900"],
});

import ContextWrapper from "@/app/contextWrapper";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <ContextWrapper>
          <Header />
          {children}
        </ContextWrapper>
      </body>
    </html >
  );
}
