'use client';
import Lines from "@/components/lines";
import Image from "next/image";
import InfoPopover from "@/components/info-popover";

export default function Section3() {

  return (
    <section className="relative bg-white pt-20 scroll-mt-8" id="section-5">
      <Lines verticalClassName="pl-[152px] pr-[152px]" sectionName="section-5" rows={[]} columnsNumber={2} colorClass="bg-blue-900/10" />
      <div className="container px-[150px] flex justify-between items-start">
        <div className="flex pb-[126px] gap-[69px]">
          <div className="w-[630px] text-green-700 space-y-5 pb-10">
            <h2 className="text-4xl font-medium pb-16">Towards data streaming for efficient uptake by users.</h2>
            <div className="max-w-[487px]">
              <h3 className="text-2xl pb-5">Current practice is that data generated from lower-resolution climate models is stored to disk.</h3>
              <div>
                <p className="pb-5">However, this approach is no longer suitable for the km-scale simulations produced by the digital twin, which call for users to be able to read and capture the information they need while the digital twin is running.
                </p>
                <p>
                  This challenge is solved by the streaming <InfoPopover
                    content={<>
                      The streaming of the model output gives users immediate access to the complete set of climate data generated by the models in a standardised format across different models and model components (source: <a target="_blank" className="hover:underline" href="https://www.ecmwf.int/">ECMWF</a>)</>
                    }
                  >concept</InfoPopover>, which brings the climate models and impact models within the same workflow, significantly transforming the way climate research has been performed and adopting a user-centred setup. Data streaming allows the output of the digital twin to be handled on-the-fly as it is being produced, therefore lowering memory requirements significantly.
                </p>
              </div>
            </div>
          </div>
        </div>
        <Image
          alt=""
          className="mr-10"
          src="/images/home-towards-data.svg"
          width={1160}
          height={742}
        />
      </div>
    </section >);
};