global_video:
    cmap: "viridis"
    scale: 1

hurricane_10km_render_params:
    cmap: "Blues_r"
    scale: 4
    bbox:
        minx: -88.23
        miny: 21.37
        maxx: -51.77
        maxy: 42.37

hurricane_100km_render_params:
    cmap: "viridis"
    scale: 20
    bbox:
        minx: -84.088
        miny: 15.89
        maxx: -55.88
        maxy: 41.15

amazonia_10km_render_params:
    cmap: "viridis"
    scale: 4
    bbox:
        minx: -79.72
        miny: -16.60
        maxx: -45.27
        maxy: 7.672

temperature_10km_render_params:
    cmap: "winter"
    scale: 4
    bbox:
        minx: -12.1350
        miny: 32.5146
        maxx: 4.7930
        maxy: 44.1825

amazonia_100km_render_params:
    cmap: "Greens_r"
    scale: 20
    bbox:
        minx: -67.53
        miny: -8.55
        maxx: -47.76
        maxy: 8.64


sst_10km_render_params:
    cmap: "plasma"
    scale: 4
    bbox:
        minx: -129
        miny: -7
        maxx: -93
        maxy: 8.5